### ISSUE TITLE
Changes in 1.0.6 breaks babel-eslint

### ISSUE THREAD

**Issue by alexeyraspopov** [babel/acorn-to-esprima#4]
See this https://github.com/babel/acorn-to-esprima/compare/v1.0.5...v1.0.6
And this https://github.com/babel/babel-eslint/issues/207

**Comment by alexeyraspopov** [comment]
TBH, this change breaks backward compatibility so it means someone used semver incorrectly.

**Comment by hzoo** [comment]
I didn't know it would break at the time it I wouldn't call it using semver incorrectly but yeah I can revert.

**Comment by hzoo** [comment]
Reverted and made 1.0.7. If you read the change it shouldn't be there in the first place. Look at https://github.com/eslint/eslint/issues/4415.
